/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GerenciaController;

/**
 *
 * @author Martin, Janaina, Nicolle, Rafael
 */
public class ClienteBotoesView extends javax.swing.JPanel {
    
    /**
     * Creates new form BotoesClienteView
     */
    public ClienteBotoesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIncluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnListarSobrenome = new javax.swing.JButton();

        btnIncluir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnIncluir.setText("Incluir");

        btnAtualizar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setActionCommand("");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnListar.setText("Listar por Nome");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnListarSobrenome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnListarSobrenome.setText("Listar por Sobrenome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIncluir)
                .addGap(36, 36, 36)
                .addComponent(btnAtualizar)
                .addGap(47, 47, 47)
                .addComponent(btnExcluir)
                .addGap(39, 39, 39)
                .addComponent(btnListar)
                .addGap(40, 40, 40)
                .addComponent(btnListarSobrenome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListarSobrenome)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcluir)
                        .addComponent(btnListar))
                    .addComponent(btnAtualizar)
                    .addComponent(btnIncluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAtualizar, btnExcluir, btnIncluir, btnListar, btnListarSobrenome});

    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnListarSobrenome;
    // End of variables declaration//GEN-END:variables

  public void setController(GerenciaController controller) {
        this.btnListar.addActionListener(e -> controller.listarCliente());
        this.btnAtualizar.addActionListener(e -> controller.atualizarCliente());
        this.btnExcluir.addActionListener(e -> controller.excluirCliente());
        this.btnIncluir.addActionListener(e -> controller.incluirCliente());
        this.btnListarSobrenome.addActionListener(e -> controller.listarClienteSobrenome());
    }
}
