/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.cliente.Cliente;
import Model.conta.Conta;
import Model.conta.ContaCorrente;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class ContaCorrenteFormularioView extends javax.swing.JPanel {

    /**
     * Creates new form FormularioContaView
     */
    public ContaCorrenteFormularioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDepositoInicial = new javax.swing.JTextField();
        txtLimite = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Deposito Inicial:    R$");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Limite:                       R$");

        txtLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDepositoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(txtLimite))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDepositoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLimiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLimiteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDepositoInicial;
    private javax.swing.JTextField txtLimite;
    // End of variables declaration//GEN-END:variables

    public ContaCorrente getContaCorrente(){
        ContaCorrente cc = new ContaCorrente();

        // fazer un loop em quanto nao digite correto, mostra uma mesagem de erro
             try{
                double dep_ini = Double.parseDouble(txtDepositoInicial.getText());
                double limite = Double.parseDouble(txtLimite.getText());
                cc.setDepositoInicial(dep_ini);
                cc.setLimite(limite);
                cc.setSaldo(dep_ini);
                return cc;
             }catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage(),"Atenção" ,JOptionPane.ERROR_MESSAGE);
                cc = null;
                return cc;
             }
//        if(dep_ini != 0.0){cc.setDepositoInicial(dep_ini);
//        cc = null;
//        }     
//        if(limite != 0.0){cc.setLimite(limite);
//        cc = null;
//        }
        
    }

    void setVisible() {
       txtDepositoInicial.setEnabled(true);
       txtLimite.setEnabled(true);
    }

    void setNull() {
        txtDepositoInicial.setEnabled(false);
       txtLimite.setEnabled(false);
    }
    
   /* public void setNumConta(Conta conta){
        if(cliente == null){
            cliente = new Cliente();
            cliente.setName("");
}
        
        labelConta.setText(conta.getNum());
    } 
    
    
    }
*/    
    
}
