/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GerenciaController;
import Model.conta.Conta;

/**
 *
 * @author nicol
 */
public class ManipulaBuscaView extends javax.swing.JPanel {
    
    GerenciaController controller;
    /**
     * Creates new form ManterBuscaView
     */
    public ManipulaBuscaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CpfBusca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        labelNumC = new javax.swing.JLabel();
        BtnBuscar = new javax.swing.JButton();
        labelNomeC = new javax.swing.JLabel();
        labelTipoC = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("CPF");

        CpfBusca.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("Busca por CPF");

        labelNumC.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelNumC.setText("Número da Conta");

        BtnBuscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BtnBuscar.setText("Buscar");

        labelNomeC.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelNomeC.setText("Nome do Cliente");

        labelTipoC.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelTipoC.setText("Tipo de Conta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelNumC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelTipoC))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CpfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(BtnBuscar)))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CpfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnBuscar))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNumC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomeC)
                    .addComponent(labelTipoC))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JTextField CpfBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelNomeC;
    private javax.swing.JLabel labelNumC;
    private javax.swing.JLabel labelTipoC;
    // End of variables declaration//GEN-END:variables

    public void setController(GerenciaController controller){
        this.controller = controller;
        BtnBuscar.addActionListener(e -> controller.setClientebyCpf());
    }
    
    public long getCpf(){
        long cpf = 0;
        try{
            if(CpfBusca.getText().equalsIgnoreCase("")) throw new RuntimeException("Preencha o campo do Cpf");
            cpf = Long.parseLong(CpfBusca.getText());
            return cpf;
        }catch(Exception e){
            throw new RuntimeException(e.getMessage());
        }
        
    }
    
    public void setContaManipula(Conta c){
        labelNomeC.setText("Nome do Cliente: "+c.getCliente().getNome());
        labelNumC.setText("Número da Conta: "+c.getNum());
        labelTipoC.setText("Tipo de Conta: "+c.getTipo());
    }
}
